
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Bashirli
 */
public class Main extends javax.swing.JFrame {
int oyuncu_sayi=0;
 int prog_bitdi=0; 
 String o1,o2;
    /** Creates new form Main */
    public Main() {
  
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        oyuncu_ad = new javax.swing.JTextField();
        oyuncu_soyad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        oyuncu_yarart = new javax.swing.JButton();
        oyuncunu_duzelt = new javax.swing.JButton();
        oyuncunu_sil = new javax.swing.JButton();
        oyuna_basla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Xoş gelmisiniz!");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Oyunçuları yaradın.");

        jLabel3.setText("Ad");

        jLabel4.setText("Soyad");

        jTable1.setBackground(new java.awt.Color(255, 153, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Oyunçu", "Ad", "Soyad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        oyuncu_yarart.setText("Oyunçu yarat");
        oyuncu_yarart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oyuncu_yarartActionPerformed(evt);
            }
        });

        oyuncunu_duzelt.setText("Oyunçunu düzelt");
        oyuncunu_duzelt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oyuncunu_duzeltActionPerformed(evt);
            }
        });

        oyuncunu_sil.setText("Oyunçunu sil");
        oyuncunu_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oyuncunu_silActionPerformed(evt);
            }
        });

        oyuna_basla.setText("Oyuna başla");
        oyuna_basla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oyuna_baslaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(469, 469, 469)
                        .addComponent(oyuncu_yarart))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel3)
                        .addGap(391, 391, 391)
                        .addComponent(oyuncunu_duzelt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(469, 469, 469)
                        .addComponent(oyuna_basla))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(oyuncu_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(oyuncu_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(469, 469, 469)
                        .addComponent(oyuncunu_sil))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(55, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(oyuncu_yarart)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3))
                    .addComponent(oyuncunu_duzelt))
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addGap(11, 11, 11)
                .addComponent(oyuna_basla))
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(oyuncu_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(oyuncu_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(oyuncunu_sil))
            .addGroup(layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oyuncu_yarartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oyuncu_yarartActionPerformed
        // TODO add your handling code here:
        
        if(problem_tapma(oyuncu_ad.getText())==0||problem_tapma(oyuncu_soyad.getText())==0){
            return;
        }
        
        
        oyuncu_sayi++;
         
         if(oyuncu_sayi<=2){
         DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        Object [] sira={oyuncu_sayi,oyuncu_ad.getText(),oyuncu_soyad.getText()};
        if(oyuncu_sayi==1){
            o1=oyuncu_ad.getText();
        }else if(oyuncu_sayi==2){
            o2=oyuncu_ad.getText();
        }
        model.addRow(sira);
         }else{
             JOptionPane.showMessageDialog(this, "Maksimum sayda oyuncu yaradildi."); JOptionPane.showMessageDialog(this, "Maksimum sayda oyuncu yaradildi.");
         }
        
    }//GEN-LAST:event_oyuncu_yarartActionPerformed

    private void oyuncunu_duzeltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oyuncunu_duzeltActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
         int setr=jTable1.getSelectedRow();
         if(setr==-1){
              JOptionPane.showMessageDialog(this, "Oyunçu seçilmeyib");
         }else{
         model.setValueAt(oyuncu_ad.getText(), setr, 1);
        model.setValueAt(oyuncu_soyad.getText(), setr, 2);
        if(setr==0){
            o1=oyuncu_ad.getText();
        }else if(setr==1){
            o2=oyuncu_ad.getText();
        }
         }    
    }//GEN-LAST:event_oyuncunu_duzeltActionPerformed
    
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
        int setr=jTable1.getSelectedRow();
        
        oyuncu_ad.setText(model.getValueAt(setr, 1).toString());
        oyuncu_soyad.setText(model.getValueAt(setr, 2).toString());
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void oyuncunu_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oyuncunu_silActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
         int setr=jTable1.getSelectedRow();
           if(setr==-1){
              JOptionPane.showMessageDialog(this, "Oyunçu seçilmeyib");
         }else{
               oyuncu_sayi--;
         model.removeRow(setr);
         
         oyuncu_ad.setText("");
         oyuncu_soyad.setText(""); 
           }
    }//GEN-LAST:event_oyuncunu_silActionPerformed

    private void oyuna_baslaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oyuna_baslaActionPerformed
        // TODO add your handling code here:
        
        if(oyuncu_sayi<2){
            JOptionPane.showMessageDialog(this, "Yeterli oyuncu yaradilmayib.");
            return;
        }
       DefaultTableModel model=(DefaultTableModel)jTable1.getModel();

       
                JOptionPane.showMessageDialog(this, "Oyun baslayir...");
   Oyun oyun=new Oyun();
   oyun.o1=o1;
   oyun.o2=o2;
        setVisible(false);
        oyun.setVisible(true);
  
    }//GEN-LAST:event_oyuna_baslaActionPerformed

    public int problem_tapma(String str){
        if(str.length()==0){
            JOptionPane.showMessageDialog(this, "Ad boş buraxılmaz.");
            return 0;
        }
        
        return 1;
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton oyuna_basla;
    private javax.swing.JTextField oyuncu_ad;
    private javax.swing.JTextField oyuncu_soyad;
    private javax.swing.JButton oyuncu_yarart;
    private javax.swing.JButton oyuncunu_duzelt;
    private javax.swing.JButton oyuncunu_sil;
    // End of variables declaration//GEN-END:variables

}
