
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Bashirli
 */
public class Oyun extends javax.swing.JFrame {
 String o1,o2;
int xal1=0,xal2=0;
int round=1;
int hesab1=0,hesab2=0;
    DefaultListModel model=new DefaultListModel();
    Random random=new Random();
   
    /**
     * Creates new form Oyun
     */
    public Oyun() {
      
        initComponents();
        this.setLocationRelativeTo(null);
        neticeler.setModel(model); 
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        netice_2 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        netice_1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        neticeler = new javax.swing.JList<>();
        oyna_1 = new javax.swing.JButton();
        bitir = new javax.swing.JButton();
        oyna_2 = new javax.swing.JButton();
        oyna_random = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        mesaj = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        netice_2.setEditable(false);
        netice_2.setBackground(new java.awt.Color(255, 255, 255));
        netice_2.setColumns(20);
        netice_2.setForeground(new java.awt.Color(0, 0, 0));
        netice_2.setRows(5);
        jScrollPane1.setViewportView(netice_2);

        netice_1.setEditable(false);
        netice_1.setBackground(new java.awt.Color(255, 255, 255));
        netice_1.setColumns(20);
        netice_1.setForeground(new java.awt.Color(0, 0, 0));
        netice_1.setRows(5);
        jScrollPane2.setViewportView(netice_1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel3.setText(":");

        neticeler.setBackground(new java.awt.Color(255, 255, 255));
        neticeler.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        neticeler.setForeground(new java.awt.Color(255, 51, 51));
        jScrollPane3.setViewportView(neticeler);

        oyna_1.setText("1-ci oyna");
        oyna_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oyna_1ActionPerformed(evt);
            }
        });

        bitir.setText("Oyunu bitir");
        bitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bitirActionPerformed(evt);
            }
        });

        oyna_2.setText("2-ci oyna");
        oyna_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oyna_2ActionPerformed(evt);
            }
        });

        oyna_random.setText("Tesadüfi");
        oyna_random.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oyna_randomActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("     Neticeler");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        mesaj.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(718, 718, 718)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(oyna_1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113)
                                .addComponent(oyna_random))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(233, 233, 233)
                                .addComponent(bitir)))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(oyna_2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(mesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(125, 125, 125)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(730, 730, 730)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel3))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addComponent(mesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(oyna_1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(oyna_random, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(91, 91, 91)
                                .addComponent(bitir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(oyna_2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oyna_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oyna_1ActionPerformed
        // TODO add your handling code here:
          
        mesaj.setText(o1+" (1-ci oyunçu) zeri atır.");
        xal1=random.nextInt(5)+1;
        mesaj.setText(o1+" (1-ci oyunçu) zeri atdi.");
        netice_1.setText(String.valueOf(xal1));
       try {
        Thread.sleep(1000);
    } catch (InterruptedException ex) {
        Logger.getLogger(Oyun.class.getName()).log(Level.SEVERE, null, ex);
    }
       
         mesaj.setText(o2+" (2-ci oyunçu) zeri atır.");
        xal2=random.nextInt(5)+1;
        mesaj.setText(o2+" (2-ci oyunçu) zeri atdi.");
        netice_2.setText(String.valueOf(xal2));
   
       if(xal1>xal2){
           mesaj.setText(o1+" (1-ci oyunçu) turu qazandi.");
           hesab1++;
       }else if(xal1<xal2){
           mesaj.setText(o2+" (2-ci oyunçu) turu qazandi");
       hesab2++;
       }else{
           mesaj.setText("Tur berabere bitdi");
       hesab1++; hesab2++;
       }
       model.addElement(round+". round "+xal1+":"+xal2);
       round++;
       
    }//GEN-LAST:event_oyna_1ActionPerformed

    private void oyna_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oyna_2ActionPerformed
        // TODO add your handling code here:
           mesaj.setText(o2+" (2-ci oyunçu) zeri atır.");
        xal2=random.nextInt(5)+1;
        mesaj.setText(o2+" (2-ci oyunçu) zeri atdi.");
        netice_2.setText(String.valueOf(xal2)); 
       try {
        Thread.sleep(1000);
    } catch (InterruptedException ex) {
        Logger.getLogger(Oyun.class.getName()).log(Level.SEVERE, null, ex);
    }
       
        mesaj.setText(o1+" (1-ci oyunçu) zeri atır.");
        xal1=random.nextInt(5)+1;
        mesaj.setText(o1+" (1-ci oyunçu) zeri atdi.");
        netice_1.setText(String.valueOf(xal1));
   
       if(xal1>xal2){
           mesaj.setText(o1+" (1-ci oyunçu) turu qazandi.");
           hesab1++;
       }else if(xal1<xal2){
           mesaj.setText(o2+" (2-ci oyunçu) turu qazandi");
       hesab2++;
       }else{
           mesaj.setText("Tur berabere bitdi");
       hesab1++; hesab2++;
       }
       model.addElement(round+". round "+xal1+":"+xal2);
       round++;
       
    }//GEN-LAST:event_oyna_2ActionPerformed

    private void oyna_randomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oyna_randomActionPerformed
        // TODO add your handling code here:
        int randomselect=random.nextInt(1)+1;
        if(randomselect==1){
             mesaj.setText(o1+" (1-ci oyunçu) zeri atır.");
        xal1=random.nextInt(5)+1;
        mesaj.setText(o1+" (1-ci oyunçu) zeri atdi.");
        netice_1.setText(String.valueOf(xal1));
       try {
        Thread.sleep(1000);
    } catch (InterruptedException ex) {
        Logger.getLogger(Oyun.class.getName()).log(Level.SEVERE, null, ex);
    }
       
         mesaj.setText(o2+" (2-ci oyunçu) zeri atır.");
        xal2=random.nextInt(5)+1;
        mesaj.setText(o2+" (2-ci oyunçu) zeri atdi.");
        netice_2.setText(String.valueOf(xal2));
   
       if(xal1>xal2){
           mesaj.setText(o1+" (1-ci oyunçu) turu qazandi.");
           hesab1++;
       }else if(xal1<xal2){
           mesaj.setText(o2+" (2-ci oyunçu) turu qazandi");
       hesab2++;
       }else{
           mesaj.setText("Tur berabere bitdi");
       hesab1++; hesab2++;
       }
       model.addElement(round+". round "+xal1+":"+xal2);
       round++;
        }else if(randomselect==2){
                  mesaj.setText(o2+" (2-ci oyunçu) zeri atır.");
        xal2=random.nextInt(5)+1;
        mesaj.setText(o2+" (2-ci oyunçu) zeri atdi.");
        netice_2.setText(String.valueOf(xal2)); 
       try {
        Thread.sleep(1000);
    } catch (InterruptedException ex) {
        Logger.getLogger(Oyun.class.getName()).log(Level.SEVERE, null, ex);
    }
       
        mesaj.setText(o1+" (1-ci oyunçu) zeri atır.");
        xal1=random.nextInt(5)+1;
        mesaj.setText(o1+" (1-ci oyunçu) zeri atdi.");
        netice_1.setText(String.valueOf(xal1));
   
       if(xal1>xal2){
           mesaj.setText(o1+" (1-ci oyunçu) turu qazandi.");
           hesab1++;
       }else if(xal1<xal2){
           mesaj.setText(o2+" (2-ci oyunçu) turu qazandi");
       hesab2++;
       }else{
           mesaj.setText("Tur berabere bitdi");
       hesab1++; hesab2++;
       }
       model.addElement(round+". round "+xal1+":"+xal2);
       round++;
       
        }
    }//GEN-LAST:event_oyna_randomActionPerformed

    private void bitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bitirActionPerformed
        // TODO add your handling code here:
        if(round==1){
            JOptionPane.showMessageDialog(this, "Oyunu oynamadiniz. Oyun bitdi.");
        }else{
            if(hesab1>hesab2){
            String bildirim=o1+" oyunçu "+round+" roundda oyunu \n"
                    + "uddu.";
            
                      JOptionPane.showMessageDialog(this, bildirim);
                    
                    }else if(hesab1<hesab2){
                          String bildirim=o2+" oyunçu "+round+" roundda oyunu uddu.";
            
                      JOptionPane.showMessageDialog(this, bildirim);
                        
                    }else {
                          String bildirim=round+" roundda oyun \n"
                    + " berabere bitdi.";
            
                      JOptionPane.showMessageDialog(this, bildirim);
                        
                    }
        }
        
        
    }//GEN-LAST:event_bitirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Oyun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Oyun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Oyun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Oyun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Oyun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bitir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel mesaj;
    private javax.swing.JTextArea netice_1;
    private javax.swing.JTextArea netice_2;
    private javax.swing.JList<String> neticeler;
    private javax.swing.JButton oyna_1;
    private javax.swing.JButton oyna_2;
    private javax.swing.JButton oyna_random;
    // End of variables declaration//GEN-END:variables
}
